### ISSUE TITLE
weird sequencing

### ISSUE THREAD

**Issue by oscie57** [oscie57/tiktok-voice#15]
currently for batch processes, we have numbered files and "for file in listdir", which on some systems mess up (1, 10, 11, 12, 13...., 2, 3...) and idk a workaround

if anyone can help thatd be awesome

**Comment by Matthew0007** [comment]
So one would need a way to sort the index of the files?

**Comment by oscie57** [comment]
kinda yeah

**Comment by Matthew0007** [comment]
Okay so we should be able to create a simple sort function that’s called in the code that sorts the indices of the files before outputting it

**Comment by lynn** [comment]
This should do the trick: https://stackoverflow.com/a/4623518/257418

**Comment by oscie57** [comment]
> This should do the trick: https://stackoverflow.com/a/4623518/257418

ah awesome! i dont have time to work on this at the moment (and i dont really have anything setup), so if someone could work on this thatd be great

**Comment by Matthew0007** [comment]
I've coded a fix for this

**Comment by oscie57** [comment]
fixed
