### ISSUE TITLE
'requests' module not found

### ISSUE THREAD

**Issue by SamuelLeMire01** [oscie57/tiktok-voice#23]
i installed requests as well as all other modules but i got this message.

C:\Users\barkley\Desktop\tiktok-voice-main>py main.py -v en_us_001 -f text.txt
Traceback (most recent call last):
  File "C:\Users\fatka\Desktop\tiktok-voice-main\main.py", line 1, in <module>
    import requests, base64, random, argparse, os, playsound, time, re, textwrap
ModuleNotFoundError: No module named 'requests'

can anyone help me?

**Comment by abirabedinkhan** [comment]
just use ```python -m pip install requests``` or in the same dir open terminal and use ```python -m pip install -r requirements.txt```
