### ISSUE TITLE
Output file names

### ISSUE THREAD

**Issue by Outpizza** [oscie57/tiktok-voice#3]
I was just wondering if you're planning on adding an output file name modifier, somewhat akin to that of youtube-dl's.
Example: `-o lorem-ipsum.mp3` instead of `&& rename voice.mp3 lorem-ipsum.mp3` at the end of the command.

**Comment by oscie57** [comment]
oh yeah i could do that! i setup something similar earlier so sure!

**Comment by oscie57** [comment]
Added here! https://github.com/oscie57/tiktok-voice/commit/48288850adac0f766bebf43152d2e06cbe33829d
