### ISSUE TITLE
Some letters not registering at the end of a sentence (US Male 3)

### ISSUE THREAD

**Issue by Mintxr** [oscie57/tiktok-voice#32]
letters such as f, k, v, g
it also usually happens after i's (magic, life)
sentences like;
But Havlicek did not have a bike.
The stove was off.
She was still alive.

It usually ends in a uh or  "a lie"

**Comment by Wolfhound905** [comment]
This has nothing to do with the library. This is using **TikTok's** api, so it would be tiktoks issue
