### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by oscie57** [oscie57/tiktok-voice#8]
Hey there! I really want to make `tiktok-voice` better, so, please put any suggestions for the project here!

**Comment by SketchMaster2001** [comment]
this is what discussions is for oscie

**Comment by SketchMaster2001** [comment]
you own the repo how don't you have the option

**Comment by oscie57** [comment]
![image](https://user-images.githubusercontent.com/66192059/165786443-dd964dc6-aa4d-4302-a3de-4bc61e829d88.png)

**Comment by oscie57** [comment]
lmao moved to discussion
